[package]
name = "datagen-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu = "1.2.0"
icu_provider = "1.2.0"
icu_provider_adapters = "1.2.0"
zerovec = "0.9.4"
